#!/bin/bash

# Wrapper script that checks for user's custom after-stop script
# If it doesn't exist, creates a template with examples

USER_SCRIPT=".claude/agent-after-stop.sh"

# Check if user script exists
if [ ! -f "$USER_SCRIPT" ]; then
  echo "Creating template: $USER_SCRIPT"

  # Create .claude directory if it doesn't exist
  mkdir -p .claude

  # Create template with examples
  cat > "$USER_SCRIPT" << 'EOF'
#!/bin/bash
# Auto-generated by agent-kit plugin
# This script runs when Claude Code stops/completes work
# Uncomment and customize based on your workflow

# === Git operations ===
# Auto-commit changes
# git add .
# git commit -m "Changes by Claude Code"

# Auto-push to remote
# git push

# === Cleanup ===
# Remove temporary files
# rm -rf .tmp

# === Final checks ===
# Run tests
# bun test

# Build project
# bun run build

# === Notifications ===
# The celebrate.sh script already runs, but you can add custom notifications here

# === Your custom logic ===
# Add your commands here
EOF

  chmod +x "$USER_SCRIPT"
  echo ""
  echo "⚠️  POST-STOP HOOK NOT CONFIGURED!"
  echo "Template created at: $USER_SCRIPT"
  echo "Please uncomment or add commands to configure your post-stop workflow."
  echo ""
  exit 1
fi

# Check if script has any active (non-commented) commands
# Ignore shebang, empty lines, and comment lines
ACTIVE_LINES=$(grep -v '^#' "$USER_SCRIPT" | grep -v '^[[:space:]]*$' | wc -l)

if [ "$ACTIVE_LINES" -eq 0 ]; then
  echo ""
  echo "⚠️  POST-STOP HOOK NOT CONFIGURED!"
  echo "File exists but contains no active commands: $USER_SCRIPT"
  echo "Please uncomment or add commands to configure your post-stop workflow."
  echo ""
  exit 1
fi

# Execute user's script
bash "$USER_SCRIPT"
