#!/bin/bash

# Wrapper script that checks for user's custom after-edit script
# If it doesn't exist, creates a template with examples

USER_SCRIPT=".claude/agent-after-edit.sh"

# Check if user script exists
if [ ! -f "$USER_SCRIPT" ]; then
  echo "Creating template: $USER_SCRIPT"

  # Create .claude directory if it doesn't exist
  mkdir -p .claude

  # Create template with examples
  cat > "$USER_SCRIPT" << 'EOF'
#!/bin/bash
# Auto-generated by agent-kit plugin
# This script runs after Edit/Write operations
# Uncomment and customize based on your project

# === JavaScript/TypeScript ===
# Prettier (standalone)
# prettier --write .

# ESLint
# eslint --fix .

# Oxlint (faster alternative)
# oxlint --fix

# Biome (all-in-one)
# biome check --apply .

# === .NET ===
# Format code
# dotnet format

# CSharpier
# dotnet csharpier .

# === Your custom logic ===
# Add your commands here
EOF

  chmod +x "$USER_SCRIPT"
  echo ""
  echo "⚠️  POST-EDIT HOOK NOT CONFIGURED!"
  echo "Template created at: $USER_SCRIPT"
  echo "Please uncomment or add commands to configure your post-edit workflow."
  echo ""
  exit 1
fi

# Check if script has any active (non-commented) commands
# Ignore shebang, empty lines, and comment lines
ACTIVE_LINES=$(grep -v '^#' "$USER_SCRIPT" | grep -v '^[[:space:]]*$' | wc -l)

if [ "$ACTIVE_LINES" -eq 0 ]; then
  echo ""
  echo "⚠️  POST-EDIT HOOK NOT CONFIGURED!"
  echo "File exists but contains no active commands: $USER_SCRIPT"
  echo "Please uncomment or add commands to configure your post-edit workflow."
  echo ""
  exit 1
fi

# Execute user's script
bash "$USER_SCRIPT"
